version: "3.9"

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MARIADB_USER: dev
      MARIADB_PASSWORD: dev123
      MARIADB_DATABASE: testdb
      MARIADB_ROOT_PASSWORD: root123
    volumes:
      - ./conf/mariadb:/etc/mysql/conf.d
    ports:
      - "3306:3306"
