version: "3.9"

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MARIADB_USER: dev
      MARIADB_PASSWORD: dev123
      MARIADB_DATABASE: testdb
      MARIADB_ROOT_PASSWORD: root123
    volumes:
      - ./conf/mariadb:/etc/mysql/conf.d
    ports:
      - "3306:3306"
  
  redis:
    image: 'redis:alpine'
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - ./db-data/redis/:/data
