// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.30.2
// source: rpc_message.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// message 정의
type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_rpc_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_rpc_message_proto_rawDescGZIP(), []int{0}
}

func (x *Hello) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_rpc_message_proto protoreflect.FileDescriptor

const file_rpc_message_proto_rawDesc = "" +
	"\n" +
	"\x11rpc_message.proto\x12\x02pb\"\x19\n" +
	"\x05Hello\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msgB\x12Z\x10grpc_svr_test/pbb\x06proto3"

var (
	file_rpc_message_proto_rawDescOnce sync.Once
	file_rpc_message_proto_rawDescData []byte
)

func file_rpc_message_proto_rawDescGZIP() []byte {
	file_rpc_message_proto_rawDescOnce.Do(func() {
		file_rpc_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_message_proto_rawDesc), len(file_rpc_message_proto_rawDesc)))
	})
	return file_rpc_message_proto_rawDescData
}

var (
	file_rpc_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
	file_rpc_message_proto_goTypes  = []any{
		(*Hello)(nil), // 0: pb.Hello
	}
)
var file_rpc_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_message_proto_init() }
func file_rpc_message_proto_init() {
	if File_rpc_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_message_proto_rawDesc), len(file_rpc_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_message_proto_goTypes,
		DependencyIndexes: file_rpc_message_proto_depIdxs,
		MessageInfos:      file_rpc_message_proto_msgTypes,
	}.Build()
	File_rpc_message_proto = out.File
	file_rpc_message_proto_goTypes = nil
	file_rpc_message_proto_depIdxs = nil
}
