// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.30.2
// source: rpc_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_rpc_service_proto protoreflect.FileDescriptor

const file_rpc_service_proto_rawDesc = "" +
	"\n" +
	"\x11rpc_service.proto\x12\x02pb\x1a\x11rpc_message.proto27\n" +
	"\fHelloService\x12'\n" +
	"\vConnMessage\x12\t.pb.Hello\x1a\t.pb.Hello(\x010\x01B\x12Z\x10grpc_svr_test/pbb\x06proto3"

var file_rpc_service_proto_goTypes = []any{
	(*Hello)(nil), // 0: pb.Hello
}
var file_rpc_service_proto_depIdxs = []int32{
	0, // 0: pb.HelloService.ConnMessage:input_type -> pb.Hello
	0, // 1: pb.HelloService.ConnMessage:output_type -> pb.Hello
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_service_proto_init() }
func file_rpc_service_proto_init() {
	if File_rpc_service_proto != nil {
		return
	}
	file_rpc_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_service_proto_rawDesc), len(file_rpc_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_service_proto_goTypes,
		DependencyIndexes: file_rpc_service_proto_depIdxs,
	}.Build()
	File_rpc_service_proto = out.File
	file_rpc_service_proto_goTypes = nil
	file_rpc_service_proto_depIdxs = nil
}
